# Generated by Django 5.1.6 on 2025-03-11 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cno', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=20)),
                ('credit', models.IntegerField(default=1)),
                ('dept', models.CharField(max_length=20)),
                ('prname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sno', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=15)),
                ('year', models.IntegerField(default=1)),
                ('dept', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Enrol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=1)),
                ('midterm', models.IntegerField()),
                ('gimal', models.IntegerField()),
                ('cno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restfulapi.course')),
                ('sno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restfulapi.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sno', 'cno'), name='restful_U_S_C')],
            },
        ),
    ]
