# Generated by Django 5.1.6 on 2025-03-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('aiexplain', models.TextField()),
                ('file', models.FileField(upload_to='chatgpt/')),
                ('today', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
